version: '3.8'

services:

  prometheus:
    image: prom/prometheus:latest
    container_name: babel-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  node-exporter:
    image: prom/node-exporter:latest
    container_name: babel-node-exporter
    ports:
      - "9100:9100"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: babel-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data: